### ISSUE TITLE
website will be governance.creativecommons.org or similar.

### ISSUE THREAD

**Issue by mattl** [creativecommons/cc990#3]
if you have a preferred name, let me know.

**Comment by peterspdx** [comment]
why not simply board.cc.org?  the docs that are intended for public consumption can be located at governance.cc.org, and then linked to from the board.cc.org space.  Or am I misunderstanding?

**Comment by mattl** [comment]
Given the public/private split, maybe board.creativecommons.org works for all private and all public can live at governance.creativecommons.org? If that works for you, I will make a start on that now.

**Comment by peterspdx** [comment]
I like it.  Thanks!
